title: Third Active Data Expanding Tech
description: > # this means to ignore newlines until "baseurl:"
  써드파티 데이터의 활용성 증대를 위한 액티브 메타데이터 기반 능동형 데이터 확장 기술 개발
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Third Active Data Expanding Tech
  link: "https://github.com/ThirdActiveDataExTech"

google_site_verification: googleXXXXXXXXXXXXXXXX.html
